### ISSUE TITLE
Load file : Clarification required for forwarding-constructs towards ALT application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#4]
In the load file of ALT , we have the following forwarding constructs from ALT to ALT for updating LTPs, 
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
</head>

<body>

S.No | Forwarding-construct | fc-port-Input   operation-server
-- | -- | --
1 | ServiceRequestCausesLtpUpdateRequest | /v1/register-yourself,   /v1/embed-yourself, /v1/redirect-service-request-information,   /v1/redirect-oam-request-information, /v1/inquire-oam-request-approvals,   /v1/update-client, /v1/redirect-topology-change-information,   /v1/update-operation-key, /v1/update-operation-client,   /v1/bequeath-your-data-and-die, v1/regard-application
2 | ServiceRequestCausesLtpDeletionRequest | v1/disregard-application
3 | ServiceRequestCausesFcUpdateRequest | v1/regard-application
4 | ServiceRequestCausesFcPortDeletionRequest | v1/end-subscription

</body>

</html>

For example , for v1/regard-application , after creating LTPs for a new application, the same LTPs will be updated again by using the operation-client v1/update-ltp. Kindly Please let us know whether we have specific reason behind this or can we remove this forwardings from the load file ?

**Comment by openBackhaul** [comment]
**Decision made on the Application Call on 6th of May:**
Instead of suppressing the self-calling requests for updating the network structure (ALT calls ALT), the data structure for the application specific internal data shall be separated from the configuration data of the ALT.
Means: the configuration data of the ALT itself shall be store inside a conventional ControlConstruct, which is saved in a CONFIGfile, and the NetworkControlDomain, which represent the ALT specific application data, shall be stored in a separate APPDATAfile.

The Specification has to change in the following aspects:
- [ ] current DATAfile has to be changed into a CONFIGfile and an APPDATAfile
- [ ] the OAS has to be adapted 
  - [ ] the descriptions of the attributes at the services have to indicate the two different files
  - [ ] and potentially more
 
The Implmentation has to change in the following aspects:
- [ ] APPDATA has to be read from separate file
- [ ] Internal data structure has to be changed from the ALT specific NetworkControlDomain towards the standard ControlConstruct

**Comment by PrathibaJee** [comment]
**Adding this note for a reference :** 
In the current server side code , I removed the self-calling(ALT calls ALT) forwardings. 

The reason is , 
1. When an application calls /v1/update-all-ltps-and-fcs or /v1/update-ltp , the operation-key attribute will be removed by the calling application
2. This results in removing operation-keys for all the operation-servers/clients ( especially with /v1/update-all-ltps-and-fcs)

**Comment by openBackhaul** [comment]
After making the decision here ([comment above](https://github.com/openBackhaul/ApplicationLayerTopology/issues/4#issuecomment-1119382998)), ALT issue https://github.com/openBackhaul/ApplicationLayerTopology/issues/132 has been created to document and track the changes that are required for off-loading the topology information into a separate database.

Parts of the specification will be ALT self-calling ALT for storing changes at its own configuration into the database, which is storing the entire network topology.
