### ISSUE TITLE
/v1/delete-ltp-and-dependents  throws internal server error for Operation-clinet update if the connected operation-client does not participate in a link

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/ApplicationLayerTopology#404]
/v1/delete-ltp-and-dependents  throws internal server error for Operation-clinet update if the connected operation-client does not participate in a link

**Comment by PrathibaJee** [comment]
**Assertion failure details**
In RO Individual Services , following are the assertions that are failed because of this problem, 
1. /v1/deregister-application:: Delete LTP and dependents notified? / client delete 

Reason for the failure :
/v1/delete-ltp-and-dependents throws internal server error for operation-client update if the connected operation-client does not participate in a link
