### ISSUE TITLE
For the regarded application links are getting created but there is no callback triggered for regard-update-link

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#436]
> OperationKeyManagement Mode : Reactive mode

For the regarded application , for the received control construct , links are getting created, But there is no regard-update-link callback sent to the OperationKeyManagement application.  This makes the new regarded application's exposed API's access using default operation key.
( In protection mode this will not be a problem)

Reference :  https://github.com/openBackhaul/ApplicationLayerTopology/issues/192 

>Priority:High;
>AffectedFlow:Security/ALT:/v1/regard-application;

**Comment by DanaSunal** [comment]
Doing callbacks could result in:
`NoLivingConnectionsError: Given the configuration, the ConnectionPool was not able to find a usable Connection for this request.` 
and subsequent 
`POST /v1/list-end-points-of-link 500 25.164 ms - 55`
that is due to Elasticsearch not being able to handle a lot of requests very fast. Issue could be solved by proposal in #444
