### ISSUE TITLE
OAS : /v1/regard-application : callback /v1/list-ltps-and-fcs could be removed

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#66]
The service /v1/regard-application has two callbacks 
1. _NewApplicationCausesRequestForLatestTopologyInformation_ - which calls /v1/list-ltps-and-fcs of the regarded application
2. _NewApplicationCausesRequestForTopologyChangeInformation_ - which calls /v1/redirect-topology-change-information of the regarded application

Problem description:
When the regarded application receives /v1/redirect-topology-change-information, ALT receives the regarded application's data through /v1/update-all-ltps-and-fcs (a callback of /v1/redirect-topology-change-information) 
However, the request-body of /v1/update-all-ltps-and-fcs and the response-body of /v1/list-ltps-and-fcs are most likely having the same content which might lead ALT receiving the same data twice.

Possible solution:
The callback __NewApplicationCausesRequestForLatestTopologyInformation__ from /v1/regard-application can be removed in order to avoid redundancy.

**Comment by openBackhaul** [comment]
In regards with:
> When the regarded application receives /v1/redirect-topology-change-information, ALT receives the regarded application's data through /v1/update-all-ltps-and-fcs (a callback of /v1/redirect-topology-change-information)  

The implementation has changed.
In the definitions of the ApplicationPattern, _/v1/redirect-topology-change-information_ does no longer initiate a callback to _/v1/update-all-ltps-and-fcs_.
Information about all the LTPs and FCs get directly sent back inside the ResponseBody of the _/v1/redirect-topology-change-information_.
This change has been made, because of a hen and egg problem during embedding process.

Besides this change, it is correct that _NewApplicationCausesRequestForLatestTopologyInformation_ is redundant and shall be removed.
