### ISSUE TITLE
OAS : /v1/update-all-ltps-and-fcs : needs an update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#76]
As per current OAS, when posting /v1/update-all-ltps-and-fcs, the control-construct instance in the load-file is replaced if it is already present. 

Problem statements: 
When a new application is regarded to ApplicationLayerTopology (ALT), as a consequence, the new application's ltps-and-fcs will be created in the ALT's control-construct list (a new control-construct instance will be created). But, in the OAS specification, the summary and descriptions are explaining only for replacing an existing CC instance as below.
- the summary of /v1/update-all-ltps-and-dependents is "Existing documentation of all interfaces and internal connections will be replaced for the same CcUuid" 
- the schema description is "'Documentation of all interfaces and internal connections of an application , replace [/core-model-1-4:network-control-domain/control-construct=*/]'"

Proposal:
 Can we update the
-  _summary_ to depicts that /v1/update-all-ltps-and-fcs could accept for new applications as well 
- the _description_ to _"create or replace"_ control-construct

**Comment by openBackhaul** [comment]
1. Embedding process has changed, since creating this issue:
Old: ALT receives _/v1/regard-application_ --callback--> ALT sends _/v1/redirect-topology-change-information- to new application --callback--> New application sends _/v1/update-all-ltps-and-fcs_ to ALT
New: ALT receives _/v1/regard-application_ --callback--> ALT sends _/v1/redirect-topology-change-information_ to new application and all information about LTPs and FCs gets answered in the ResponseBody.
Since the _control-construct_ of the new application gets completed inside the ALT directly after sending _/v1/redirect-topology-change-information_, which is communicating the contacts of the ALT to the new application, **it can be assumed that the _control-construct_ always already exists in all its components whenever the new application could address the _/v1/update-all-ltps-and-fcs_ at the ALT.**
(Actually, the _/v1/update-all-ltps-and-fcs_ is not automatically addressed at all at the moment.)

2. **Can't imagine an administrator manually (e.g. by Postman) addressing "/v1/update-all-ltps-and-fcs"** for loading an entire _control-construct_ to the ALT. This use case could be put aside until it is actually requested.

3. Embedding process has also been changed for ALT, since creating this issue:
Old: Application data has been passed by the old release calling the same operations at the new application during executing _/v1/bequeath-your-data-and-die_.
New: Contact information to an external database gets passed from the old release to the new application.
Consequently, also **during executing _/v1/bequeath-your-data-and-die_, it cannot happen that _/v1/update-all-ltps-and-fcs_ gets addressed by old release of ALT while the _control-construct_ of some application doesn't already exists**.

Summary:
Currently, there is no entity (application or human), which could address _/v1/update-all-ltps-and-fcs_ while the _control-construct_ of an application does not already exist, seen. Thus, no need for change seen.

**Comment by IswaryaaS** [comment]
After changing the embedding process in version 2.0.0, the need for creating a new control-construct becomes obsolete. the current description "replace [/core-model-1-4:network-control-domain/control-construct=*/]" looks fine. 
Completely agreeing with the clarification provided on https://github.com/openBackhaul/ApplicationLayerTopology/issues/76#issuecomment-1339144447 and hence closing the issue
