### ISSUE TITLE
OAS : /v1/update-all-ltps-and-fcs description needs an update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#78]
Actual workflow:
When an application is regarded to ApplicationLayerTopology (ALT) through /v1/regard-application, ALT sends /v1/redirect-topology-change-information to the regarded application. Further the regarded application sends /v1/update-all-ltps-and-fcs to ALT (callback of /v1/redirect-topology-change-information). So, always it is an indirect fact that, _if an instance of a new application to be created in CC, it should be first regarded in ALT_ (which means an instance of the application should be present in http-client ltp of ALT's control-construct). 

Also, an application's control-construct instance in the control-construct list could be deleted only if it is disregarded in ALT's control-construct.

Problem statement : 
Currently, the /v1/update-all-ltps-and-fcs create a new CC instance even if it is not regarded in ALT CC (even if http-c entry is not present in ALT's control-construct)

Proposal:
Can we add an additional description to /v1/update-all-ltps-and-fcs that could restrict creating a new instance if it's corresponding http-client instance is not present in ALT's CC.

**Comment by openBackhaul** [comment]
Situation has changed in a couple of aspects since creation of this issue.
As described in a [comment in ALT issue#76](https://github.com/openBackhaul/ApplicationLayerTopology/issues/76#issuecomment-1339144447) there is no situation, in which calling _/v1/update-all-ltps-and-fcs_ could lead to creation of a new _control-construct_ , expected.
Consequently, the current descriptions of _/v1/update-all-ltps-and-fcs_, which are all referencing **updating an existing** _control-construct_ could be left untouched.
Thus, there is no need for restricting creation of new instances of _control-construct_  to particular conditions.

**Comment by IswaryaaS** [comment]
Thanks for clarifying the query.
